### ISSUE TITLE
Unable to start application

### ISSUE THREAD

**Issue by aodj** [YakDriver/scratchrelaxtv#29]
**Describe the bug**
Unable to run scratchrelaxtv

**Your configuration**
Brand new macbook pro, using system Python 2.7

**Steps to reproduce**
It was necessary to install pip first, since this is a new laptop; with pip installed, I ran `pip install --user scratchrelaxtv`.
With the tool installed, navigate to the Terraform modules, and attempt to run the `relaxtv` script

**Expected behavior**
The tool will work, or display help

**What happened instead**
A Python exception was raised:
```bash
alexander at Alexanders-MacBook-Pro in ~/Documents/github/infrastructure-modules/gcp/modules/web on master*
$ /Users/alexander/Library/Python/2.7/bin/relaxtv
Traceback (most recent call last):
  File "/Users/alexander/Library/Python/2.7/bin/relaxtv", line 11, in <module>
    sys.exit(main())
  File "/Users/alexander/Library/Python/2.7/lib/python/site-packages/scratchrelaxtv/cli.py", line 69, in main
    extractor = scratchrelaxtv.VarExtractor(args)
  File "/Users/alexander/Library/Python/2.7/lib/python/site-packages/scratchrelaxtv/__init__.py", line 153, in __init__
    super().__init__(args)
TypeError: super() takes at least 1 argument (0 given)
```

**Additional context**
Since I installed to the user library location (using `--user` in pip) the scripts aren't installed into $PATH.

**Comment by aodj** [comment]
Looking at the README.md i see that one of the badges lists Python 3.5, 3.6 and 3.7, which probably explains my issue. It might be good to put a simple version check in the application to stop people running it against older Python versions.

**Comment by YakDriver** [comment]
@aodj Thanks for trying out scratchrelaxtv. It's super easy to install on your macbook pro:

```console
$ brew install python3 pip3
$ pip3 install scratchrelaxtv
$ relaxtv...
```

**Comment by aodj** [comment]
Ah thanks, it was no problem to install it; I just didn't notice the Python 3 limitation when I read the README.md first. I figured I would leave the exception above in case anyone ends up in the same place and doesn't know the fix.
